### ISSUE TITLE
Suppress type ignore masks missing Tailored attributes used by cover-letter helpers

### ISSUE THREAD

**Issue by sachncs** [sachncs/gethired#6]
## Problem

`gethired/cli.py:567` returns `tailored.jds` with `# type: ignore[no-any-return]`. This `# type: ignore` exists solely to silence the type checker for an `AttributeError` that fires at runtime when the cover-letter CLI path runs. The cover-letter helper trio (`resume_for_tailored`, `jobs_for_tailored`, `merged_analysis_for_tailored`) all assume `Tailored` has `master` / `jds` / `analysis` fields that do not exist on the dataclass.

## Evidence

```python
# gethired/cli.py:557-575
def resume_for_tailored(tailored):
    master_obj = tailored.master                # AttributeError
    if master_obj is None:
        raise RuntimeError("Tailored.master not populated; cannot produce cover letter")
    return master_obj

def jobs_for_tailored(tailored) -> tuple[Job, ...]:
    return tailored.jds  # type: ignore[no-any-return]

def merged_analysis_for_tailored(tailored):
    analysis = tailored.analysis                # AttributeError
    if analysis is None:
        raise RuntimeError("Tailored.analysis not populated; cannot produce cover letter")
    return analysis
```

Reproducible:

```python
>>> from gethired.cli import resume_for_tailored
>>> from gethired.models import Tailored, Skills
>>> t = Tailored(name='x', email='x@x.com', city='x', phone='1',
...     github=None, linkedin=None, summary='', skills=Skills(categories={}),
...     experience=(), projects=(), education=(), awards=(),
...     dropped=(), rationale='', grounding=(), jobs=(), run_result=None)
>>> resume_for_tailored(t)
AttributeError: 'Tailored' object has no attribute 'master'
```

`gethired/models.py:637-656` defines `Tailored` without `master` / `jds` / `analysis`. The `# type: ignore[no-any-return]` masks the missing-attribute warning from mypy.

## Root Cause

Same root cause as the cover-letter CLI crash: the orchestrator was supposed to attach those three fields to the `Tailored` it persists, but the dataclass was never extended to declare them.

## Impact

- Suppresses a real type-checker signal — the very signal the `# noqa:` policy in `CONTRIBUTING.md` says must be fixed, not silenced.
- Lets the runtime bug slip past CI.
- Sets a bad precedent: future contributors may add more `# type: ignore`s for similar mismatches.

## Recommendation

This is the same fix as the cover-letter crash issue, applied at the type level:

1. Add `master`, `jds`, `analysis` as Optional fields on `Tailored`.
2. Populate them in `Tailor.__run`.
3. Remove the `# type: ignore[no-any-return]` on `cli.py:567`.

If for some reason the fields cannot be added, change `jobs_for_tailored` to raise the documented `RuntimeError` instead of returning `tailored.jds` directly, and remove the ignore.

## Acceptance Criteria

- [ ] `# type: ignore[no-any-return]` deleted from `gethired/cli.py:567`.
- [ ] `mypy gethired/` reports no errors.
- [ ] The cover-letter CLI path no longer crashes.

## Verification

```bash
uv run mypy gethired/
uv run gethired cover https://example.com/jd
```

## Risk

None if the underlying cover-letter fix lands first. If the field additions are deferred, change `jobs_for_tailored` to read from a separate side-channel and update the test fixtures accordingly.

**Comment by sachncs** [comment]
Resolved in PR #17.
